apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: landing-site-ingress
  namespace: backend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: landing-site.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: landing-site-service
            port:
              number: 80