apiVersion: v1
kind: Service
metadata:
  name: landing-site-service
  namespace: backend
  labels:
    app: landing-site
spec:
  type: NodePort
  selector:
    app: landing-site
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30082
    protocol: TCP