apiVersion: v1
kind: Service
metadata:
  name: landing-site-service
  namespace: backend
  labels:
    app: landing-site
spec:
  type: LoadBalancer
  selector:
    app: landing-site
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP